In [5]:
import numpy as np

In [31]:
num = np.array([56,33,12,78,52,61,25] , dtype=np.int16)

In [13]:
num.max()

78

In [15]:
num.min()

12

In [19]:
num.size

7

In [21]:
num1 = np.array([45.67, 23.56, 78.25 , 89.03])

In [25]:
num1

array([45.67, 23.56, 78.25, 89.03])

In [23]:
num1.dtype

dtype('float64')

In [ ]:
dtype.num

In [33]:
num * 2

array([112,  66,  24, 156, 104, 122,  50], dtype=int16)

In [35]:
num>40

array([ True, False, False,  True,  True,  True, False])

In [37]:
num[num>40]   ##########filtering

array([56, 78, 52, 61], dtype=int16)

# 2d array

In [39]:
M = np.array([[5,6,7], [2,4,3], [6,8,9], [0,1,3]])

In [41]:
M

array([[5, 6, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [43]:
M.ndim

2

In [45]:
M.shape

(4, 3)

In [47]:
M.size

12

In [49]:
M[0][1]

6

In [51]:
M[0,1]

6

In [53]:
M[0,1] =8

In [55]:
M

array([[5, 8, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [63]:
M.transpose()

array([[5, 2, 6, 0],
       [8, 4, 8, 1],
       [7, 3, 9, 3]])

In [59]:
M

array([[5, 8, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [61]:
M.T

array([[5, 2, 6, 0],
       [8, 4, 8, 1],
       [7, 3, 9, 3]])

In [65]:
M.reshape(6,2)

array([[5, 8],
       [7, 2],
       [4, 3],
       [6, 8],
       [9, 0],
       [1, 3]])

In [67]:
M.flatten()

array([5, 8, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [69]:
M.reshape(12)

array([5, 8, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [71]:
M.reshape(-1)

array([5, 8, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [73]:
M.reshape(-1,4)

array([[5, 8, 7, 2],
       [4, 3, 6, 8],
       [9, 0, 1, 3]])